export const APP_ROUTES = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  BOTTOM_TABS: {
    SUPERVISOR_TASKS_SCREEN: 'SUPERVISOR_TASKS_SCREEN',
    REQUEST_SCREEN: 'REQUEST_SCREEN',
    PROFILE_SCREEN: 'PROFILE_SCREEN',
  },
  REQUEST_SCREEN: 'REQUEST_SCREEN',
};
