export const APP_ROUTES = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  BOTTOM_TABS: {
    TASKS_SCREEN: 'TASKS_SCREEN',
    TASKS_TEACHER_SCREEN: 'TASKS_TEACHER_SCREEN',
    AUDIENCE_SCREEN: 'AUDIENCE_SCREEN',
    PROFILE_SCREEN: 'PROFILE_SCREEN',
  },
  REQUEST_SCREEN: 'REQUEST_SCREEN',
  TASK_DETAILS_SCREEN: 'TASK_DETAILS_SCREEN',
  NEW_TASK_SCREEN: 'NEW_TASK_SCREEN',
  NEW_AUDIENCE_SCREEN: 'NEW_AUDIENCE_SCREEN',

  NEW_TASK_TEACHER_SCREEN: 'NEW_TASK_TEACHER_SCREEN',
  TASK_TASK_DETAILS_SCREEN: 'TASK_TASK_DETAILS_SCREEN',
};
