export const APP_ROUTES = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  BOTTOM_TABS: {
    FEED_SCREEN: 'FEED_SCREEN',
    REQUEST_SCREEN: 'REQUEST_SCREEN',
    PROFILE_SCREEN: 'PROFILE_SCREEN',
  },
};
